name: regex_student_reinforce_binary
task: 'regex'
student:
  name: ReinforceStudent
  model:
    name: StudentLSTMSeq2SeqModel
    hidden_size: 512
    task_time_embed_size: 32
    src_time_embed_size: 8
    tgt_time_embed_size: 8
    task_embed_size: 128
    src_embed_size: 32
    tgt_embed_size: 32
    dropout_ratio: .0
    learning_rate: .0001
  max_timesteps: 40
teacher:
  name: ReinforceTeacher
  reward_metric: 'score'
trainer: 
  batch_size: 32
  name: ReinforceTrainer
  max_iters: 30000
  log_every: 50
  entropy_weight: 0.1
seed: 123
data_file: "corpus.json"
limit_train_data: 0
device_id: 0

